''' Paremeters related to layout of app not captured in the UI file '''

PROJECT_TABLE_COLUMN_SPACING = [70, 300, 100, 75, 75, 75, 75, 20]
PROJECT_TABLE_LEFT_ALGIN_COLUMNS = [1]
PROJECT_TABLE_EDITABLE_COLUMNS = [1]
PROJECT_TABLE_ROW_HEIGHT = 50
