# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/PyQtApps/ToDoQt/UI/ToDoApp.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ToDoLayout(object):
    def setupUi(self, ToDoLayout):
        ToDoLayout.setObjectName("ToDoLayout")
        ToDoLayout.resize(685, 630)
        ToDoLayout.setMinimumSize(QtCore.QSize(685, 630))
        ToDoLayout.setMaximumSize(QtCore.QSize(685, 630))
        self.centralwidget = QtWidgets.QWidget(ToDoLayout)
        self.centralwidget.setObjectName("centralwidget")
        self.addNewTask_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.addNewTask_pushButton.setGeometry(QtCore.QRect(500, 2, 151, 41))
        self.addNewTask_pushButton.setObjectName("addNewTask_pushButton")
        self.newTask_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.newTask_lineEdit.setGeometry(QtCore.QRect(210, 10, 271, 31))
        self.newTask_lineEdit.setMaxLength(20)
        self.newTask_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.newTask_lineEdit.setObjectName("newTask_lineEdit")
        self.pending_listView = QtWidgets.QListView(self.centralwidget)
        self.pending_listView.setGeometry(QtCore.QRect(20, 80, 211, 281))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.pending_listView.setPalette(palette)
        self.pending_listView.setObjectName("pending_listView")
        self.inProgress_listView = QtWidgets.QListView(self.centralwidget)
        self.inProgress_listView.setGeometry(QtCore.QRect(240, 80, 211, 281))
        self.inProgress_listView.setObjectName("inProgress_listView")
        self.done_listView = QtWidgets.QListView(self.centralwidget)
        self.done_listView.setGeometry(QtCore.QRect(460, 80, 211, 281))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.done_listView.setPalette(palette)
        self.done_listView.setObjectName("done_listView")
        self.description_textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.description_textEdit.setEnabled(True)
        self.description_textEdit.setGeometry(QtCore.QRect(20, 410, 651, 141))
        self.description_textEdit.setReadOnly(False)
        self.description_textEdit.setObjectName("description_textEdit")
        self.pending_label = QtWidgets.QLabel(self.centralwidget)
        self.pending_label.setGeometry(QtCore.QRect(20, 50, 201, 21))
        self.pending_label.setAlignment(QtCore.Qt.AlignCenter)
        self.pending_label.setObjectName("pending_label")
        self.inProgress_label = QtWidgets.QLabel(self.centralwidget)
        self.inProgress_label.setGeometry(QtCore.QRect(240, 50, 201, 21))
        self.inProgress_label.setAlignment(QtCore.Qt.AlignCenter)
        self.inProgress_label.setObjectName("inProgress_label")
        self.done_label = QtWidgets.QLabel(self.centralwidget)
        self.done_label.setGeometry(QtCore.QRect(460, 50, 201, 21))
        self.done_label.setAlignment(QtCore.Qt.AlignCenter)
        self.done_label.setWordWrap(False)
        self.done_label.setObjectName("done_label")
        self.saveChanges_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveChanges_pushButton.setEnabled(False)
        self.saveChanges_pushButton.setGeometry(QtCore.QRect(190, 365, 150, 40))
        self.saveChanges_pushButton.setObjectName("saveChanges_pushButton")
        self.delete_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.delete_pushButton.setEnabled(False)
        self.delete_pushButton.setGeometry(QtCore.QRect(350, 365, 100, 40))
        self.delete_pushButton.setObjectName("delete_pushButton")
        self.editDescription_label = QtWidgets.QLabel(self.centralwidget)
        self.editDescription_label.setGeometry(QtCore.QRect(30, 376, 151, 20))
        self.editDescription_label.setObjectName("editDescription_label")
        self.backup_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.backup_pushButton.setGeometry(QtCore.QRect(20, 560, 121, 41))
        self.backup_pushButton.setObjectName("backup_pushButton")
        self.close_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.close_pushButton.setGeometry(QtCore.QRect(550, 560, 121, 41))
        self.close_pushButton.setObjectName("close_pushButton")
        self.upload_pushButtod = QtWidgets.QPushButton(self.centralwidget)
        self.upload_pushButtod.setGeometry(QtCore.QRect(150, 560, 121, 41))
        self.upload_pushButtod.setObjectName("upload_pushButtod")
        ToDoLayout.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ToDoLayout)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 685, 26))
        self.menubar.setObjectName("menubar")
        ToDoLayout.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ToDoLayout)
        self.statusbar.setObjectName("statusbar")
        ToDoLayout.setStatusBar(self.statusbar)

        self.retranslateUi(ToDoLayout)
        QtCore.QMetaObject.connectSlotsByName(ToDoLayout)

    def retranslateUi(self, ToDoLayout):
        _translate = QtCore.QCoreApplication.translate
        ToDoLayout.setWindowTitle(_translate("ToDoLayout", "MainWindow"))
        self.addNewTask_pushButton.setText(_translate("ToDoLayout", "Add New Item"))
        self.pending_label.setText(_translate("ToDoLayout", "Pending"))
        self.inProgress_label.setText(_translate("ToDoLayout", "In Progress"))
        self.done_label.setText(_translate("ToDoLayout", "Done"))
        self.saveChanges_pushButton.setText(_translate("ToDoLayout", "Save Changes"))
        self.delete_pushButton.setText(_translate("ToDoLayout", "Delete"))
        self.editDescription_label.setText(_translate("ToDoLayout", "Edit Description"))
        self.backup_pushButton.setText(_translate("ToDoLayout", "Backup"))
        self.close_pushButton.setText(_translate("ToDoLayout", "Close"))
        self.upload_pushButtod.setText(_translate("ToDoLayout", "Upload"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ToDoLayout = QtWidgets.QMainWindow()
    ui = Ui_ToDoLayout()
    ui.setupUi(ToDoLayout)
    ToDoLayout.show()
    sys.exit(app.exec_())

